tickers:
  - TQQQ
  - SQQQ
  - SPY
  - QQQ
  - IWM
  - XLK
  - XLC
  - XLY
  - SMH
  - SOXX
  - MTUM
  - SOXL
  - NVDA
  - MSFT
  - META
  - TSLA
  - AVGO
  - AMD
  - ARM
  - MU
  - ANET
  - PLTR
  - CRWD
  - PANW
  - COIN
  - HOOD